### ISSUE TITLE
Add hardware details for F320

### ISSUE THREAD

**Issue by sshahzaiib** [MoKee/android_external_mokee_ServerController#72]
'f320' =>array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '32GB',
                     'battery' => '2650 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),

**Comment by martincz** [comment]
Thanks, but commit via our gerrit code review please.
